Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BC_IS413_Assignment8.Models;
using Microsoft.AspNetCore.Mvc;

namespace BC_IS413_Assignment8.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using BC_IS413_Assignment8.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BC_IS413_Assignment8.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IAmazonBooksRepository repository;
        public NavigationMenuViewComponent (IAmazonBooksRepository r)
        {
            repository = r;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/BookSummary.cshtml
@model Book
 
<tr>
    <td>
        <form id="@Model.BookId" asp-page="/Cart" method="post">
            <input type="hidden" asp-for="BookId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text p-1"
                  @Model.Price>
                <button type="submit" class="btn-success btn-sm pull-right">
                    Add to Cart
                </button>
            </span>
        </form>
    </td>
    <td>@Model.BookId</td>
    <td>@Model.Title</td>
    <td>@(Model.AuthorFirst + " " + Model.AuthorMiddle + " " + Model.AuthorLast)</td>
    <td>@Model.Publisher</td>
    <td>@Model.ISBN</td>
    <td>@Model.Classification</td>
    <td>@Model.Category</td>
    <td>$@Model.Price</td>
    <td>@Model.NumOfPages</td>
</tr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"]</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/Amazon-Books-Logo.png" alt="" width="125" /></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        </ul>
                    </div>
                    <div class="float-right">
                        <vc:cart-summary />
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <div class="row text-center">
                <div class="col">
                    <h1 class="display-4">Welcome to AmazonBooks.com</h1>
                    <p>Learn more about <a class="text-decoration-none" href="https://www.aboutamazon.com/about-us">our history</a>.</p>
                </div>
            </div>
        </div>
        <main role="main">
            <div class="container">
                <div class="row">
                    <div class="col-2">
                        <vc:navigation-menu />
                    </div>

                    <div class="pb-3 col-10">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </main>


        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; Amazon Books LLC.
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>