Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BC_IS413_Assignment8.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();

        public virtual void AddItem (Book book, int quantity)
        {
            //Using Linq to SQL query
            CartLine line = Lines
                .Where(b => b.Book.BookId == book.BookId)
                .FirstOrDefault();

            if (line == null)
            {
                Lines.Add(new CartLine
                    {
                        Book = book,
                        Quantity = quantity
                    });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Book book) =>
            Lines.RemoveAll(x => x.Book.BookId == book.BookId);

        public virtual void Clear() => Lines.Clear();

        //decimals are for money and financial. Doubles are for science.
        public decimal ComputeTotalSum() => Lines.Sum(e => e.Book.Price * e.Quantity);

        public class CartLine
        {
            public int CartLineID { get; set; }
            public Book Book { get; set; }
            public int Quantity { get; set; }
        }
    }
}

Pages/Buy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BC_IS413_Assignment8.Infrastructure;
using BC_IS413_Assignment8.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BC_IS413_Assignment8.Pages
{
    public class BuyModel : PageModel
    {
        private IAmazonBooksRepository repository;

        public BuyModel (IAmazonBooksRepository repo)
        {
            repository = repo;
        }

        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
        
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.BookId == bookId);

            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart(); //?? is if null, then

            Cart.AddItem(book, 1);

            HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BC_IS413_Assignment8.Infrastructure;
using BC_IS413_Assignment8.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BC_IS413_Assignment8.Pages
{
    public class CartModel : PageModel
    {
        private IAmazonBooksRepository repository;

        public CartModel (IAmazonBooksRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }

        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
        
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.BookId == bookId);

            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart(); //?? is if null, then

            Cart.AddItem(book, 1);

            //HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Book.BookId == bookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Cart.cshtml
@page
@model BC_IS413_Assignment8.Pages.CartModel

<div class="row">
    <div class="col">
        <h2>Your Cart</h2>
    </div>
</div>

<div class="row">
    <div class="col">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Book</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col">Subtotal</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model.Cart.Lines)
                {
                    <tr>
                        <td class="text-left">@line.Book.Title </td>
                        <td class="text-center">@line.Quantity</td>
                        <td class="text-right">$@line.Book.Price</td>
                        <td class="text-right">@((line.Quantity * line.Book.Price).ToString("c"))</td> <!--ToString("c") specifies currency and adds a $ to the front-->
                        <td class="text-center">
                            <form asp-page-handler="Remove" method="post">
                                <input type="hidden" name="BookId"
                                       value="@line.Book.BookId" />
                                <input type="hidden" name="returnUrl"
                                       value="@Model.ReturnUrl" />
                                <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c")</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<div class="text-center row">
    <div class="col">
        <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    </div>
</div>